### ISSUE TITLE
ProvidesPackage syntax error

### ISSUE THREAD

**Issue by CrisisStudent** [jlelong/solutions#1]
Hi,

when I include your package I get following error:

! Missing number, treated as zero.

This happens also when I try to run your example codes.

Best,
CrisisStudent

**Comment by jlelong** [comment]
Can you post a minimal example to reproduce the issue?

**Comment by CrisisStudent** [comment]
I also used your insmaple example to check if it is related to my example, so you can use that (I just removed the a4wide package):

\documentclass[a4paper,11pt]{article}
\usepackage{t1enc,lmodern,enumitem}
\usepackage{amsmath,amsthm,amssymb}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{solutions}

%--------------------------------------------
\hbadness=10000
\emergencystretch=\hsize
\tolerance=9999
\textheight=9.0in
%--------------------------------------------

\begin{document}
\begin{center}
  {\large \bf Testing the \texttt{solutions} package with \texttt{inline} option.}
\end{center}
\vspace{1em}

\input coretest.tex

\pagebreak
\end{document}

These are the errors I get:

![image](https://user-images.githubusercontent.com/78561474/114684696-7356b800-9d11-11eb-8279-23900c4ca491.png)

**Comment by jlelong** [comment]
I cannot reproduce the issue. When I run `pdflatex` on your file, everything works fine.
Can you post the output of the LaTeX compiler?

**Comment by CrisisStudent** [comment]
Hope this is what you meant (sorry, I am bit low level user, but I really like your package! ;) )
[test2.log](https://github.com/jlelong/solutions/files/6309761/test2.log)

**Comment by jlelong** [comment]
The logs say that there is an error on line 7 of your `.tex` file. The package `solutions` is loaded properly

```
! Missing number, treated as zero.
<to be read again>
                   d
l.7
```

It is as if there were a lost character in your preamble before `begin{document}`.

**Comment by CrisisStudent** [comment]
It always says that the error is one line right after the package is loaded, e.g. if you move the package to line 9 it will give error in line 10 (tried that...). Also tried to use TexWorks rather than Texmaker, and same result.

Anyway, I guess I am out of luck, sorry to bother you.

**Comment by jlelong** [comment]
Could you upload your version of `solutions.sty` et `test.tex`. Just in case, there is a hidden character somewhere.

**Comment by CrisisStudent** [comment]
Here you go:

[Test.zip](https://github.com/jlelong/solutions/files/6310483/Test.zip)

Just to be clear, I have downloaded them from here just today.

**Comment by jlelong** [comment]
Hum, it seems that MikTeX is more strict than TeXLive on the syntax of `ProvidesPackage`. Try to replace the line of `solutions.sty` containing `ProvidesPackage` by

```
\ProvidesPackage{solutions}[2021/04/14 package solutions, v1.1]
```

**Comment by CrisisStudent** [comment]
Bingo!

Thanks a lot for your help, I am looking forward to using the package!
